version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz

    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: "{{ .Env.PROJECT_NAME }}"
    # GOARM to specify which 32-bit arm version to use if there are multiple versions
    # from the build section. Brew formulas support atm only one 32-bit version.
    # Default is 6 for all artifacts or each id if there a multiple versions.
    goarm: 6

    # GitHub/GitLab repository to push the formula to
    repository:
      owner: "{{ .Env.GITHUB_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
      branch: "{{ .Env.GITHUB_BRANCH }}"

    # Template for the url which is determined by the given Token (Github or gitlab)
    url_template: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: "{{ .Env.GITHUB_AUTHOR_NAME }}"
      email: "{{ .Env.GITHUB_AUTHOR_EMAIL }}"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"

    # Your app's description.
    description: "{{ .Env.PROJECT_DESCRIPTION }}"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: false

    # Packages your package depends on.
    dependencies:
      - name: go
        type: build

    # So you can `brew test` your formula. 
    # This is also picked up by the homebrew-core bot
    # Default is empty.
    test: |
      assert shell_output("#{bin}/tfren version")

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "tfren"

scoops:
  - name: "{{ .Env.PROJECT_NAME }}"
    url_template: "http://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: "{{ .Env.GITHUB_AUTHOR_NAME }}"
      email: "{{ .Env.GITHUB_AUTHOR_EMAIL }}"
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    description: "{{ .Env.PROJECT_DESCRIPTION }}"
    license: MIT
    persist:
      - "data"
      - "config.toml"
    repository:
      owner: "{{ .Env.GITHUB_OWNER }}"
      name: scoop-bucket
      branch: "{{ .Env.GITHUB_BRANCH }}"
      token: "{{ .Env.GITHUB_TOKEN }}"
      